right_format = """$status"""

[aws]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[nodejs]
symbol = "◑ "

[status]
disabled = false
format = '[$symbol $status]($style) '

[sudo]
disabled = false
